name: WindSpigot PR Build

on:
  pull_request:

jobs:
  cleanup-and-build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip]')"
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 18.0.1
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 18.0.1
        server-id: github
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean package --file pom.xml
